const { merge } = require("webpack-merge");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const common = require("./webpack.common.js");

module.exports = (env, argv) => {
    const base = common(env, argv);
    // Remove the CleanWebpackPlugin from common so we can replace it
    // with one that preserves the types/ directory (generated by tsc)
    base.plugins = base.plugins.filter((p) => !(p instanceof CleanWebpackPlugin));

    return merge(base, {
        entry: {
            app: "./src/index.ts",
            // NOTE we also get a `styles.bundle.js`, ignore this
            styles: "./src/styles/index.css",
        },
        mode: "development",
        watch: true,
        // don't bundle highlight.js or its languages; we expect consumers to supply these themselves
        externals: function ({ request }, callback) {
            if (/^highlight.js/.test(request)) {
                return callback(null, {
                    commonjs: request,
                    commonjs2: request,
                    root: "hljs",
                });
            }

            callback();
        },
        devtool: "source-map",
    });
};
